# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

name: license
kind: pipeline
type: docker

steps:
  - name: check
    image: docker.io/library/golang:1.16
    pull: always
    commands:
      - go get -u github.com/google/addlicense
      - addlicense -c "SIGHUP s.r.l" -v -l bsd -y "2017-present" --check .
---
name: policeman
kind: pipeline
type: docker

depends_on:
  - license

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    image: quay.io/sighup/policeman
    pull: always
    environment:
      # Identifies false positives like missing 'selector'.
      # Doing this is valid for Kustomize patches
      VALIDATE_KUBERNETES_KUBEVAL: "false"
      # Some duplicated code is intended.
      VALIDATE_JSCPD: "false"
      # Disable natural language checks
      VALIDATE_NATURAL_LANGUAGE: "false"
    depends_on:
      - clone

  - name: render
    image: quay.io/sighup/e2e-testing:1.1.0_0.7.0_3.1.1_1.9.4_1.24.1_3.8.7_4.21.1
    pull: always
    depends_on:
      - clone
    commands:
      - furyctl vendor -H
      - kustomize build . > distribution.yml

  - name: deprek8ion
    image: eu.gcr.io/swade1987/deprek8ion:1.1.34
    pull: always
    depends_on:
      - render
    commands:
      - /conftest test -p /policies distribution.yml

---
name: e2e-kubernetes-1.22
kind: pipeline
type: docker

node:
  runner: internal

depends_on:
  - policeman

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**
      - refs/heads/master
      - refs/heads/main
      - refs/heads/release-v**

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v1.24.0
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: custom-cluster-122
      pipeline_id: cluster-122
      local_kind_config_path: tests/config/kind-config-custom
      cluster_version: '1.22.0'
      instance_path: /shared
      instance_size: 2-extra-large
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password

  - name: test
    image: quay.io/sighup/e2e-testing:1.1.0_0.7.0_3.1.1_1.9.4_1.24.1_3.8.7_4.21.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-122
      - bats -t tests/install.sh
      - bats -t tests/networking.sh
      - bats -t tests/monitoring.sh
      - bats -t tests/logging.sh
      - bats -t tests/ingress.sh
      - bats -t tests/dr.sh
      - bats -t tests/opa.sh

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v1.24.0
    depends_on: [ test ]
    settings:
      action: destroy
      pipeline_id: cluster-122
      instance_size: 2-extra-large
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}

---
name: release
kind: pipeline
type: docker

depends_on:
  - e2e-kubernetes-1.22

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

steps:
  - name: prepare-canonical-json
    image: registry.sighup.io/poc/fury-repo-automations:v0.0.3
    pull: always
    depends_on: [ clone ]
    commands:
      - spock distro-json -r=False -v=${DRONE_TAG}
    when:
      ref:
        include:
          - refs/tags/**

  - name: prepare-release-manifests
    image: quay.io/sighup/e2e-testing:1.1.0_0.7.0_3.1.1_1.9.4_1.24.1_3.8.7_4.21.1
    pull: always
    depends_on: [ clone ]
    environment:
      RELEASE_MANIFESTS_PATH: fury-distribution-${DRONE_TAG}.yml
    commands:
      - furyctl vendor -H
      - kustomize build . > $${RELEASE_MANIFESTS_PATH}
      - cp tests/config/kind-config-custom kind-config-${DRONE_TAG}.yml
    when:
      ref:
        include:
          - refs/tags/**

  - name: prepare-release-notes
    image: quay.io/sighup/fury-release-notes-plugin:3.7_2.8.4
    pull: always
    depends_on: [ clone ]
    settings:
      release_notes_file_path: release-notes.md
    when:
      ref:
        include:
          - refs/tags/**

  - name: publish-prerelease
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-canonical-json
      - prepare-release-manifests
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: skip
      files:
        - fury-distribution-${DRONE_TAG}.yml
        - kind-config-${DRONE_TAG}.yml
        - Furyfile.yml
        - kustomization.yaml
        - kfd-canonical-definition-${DRONE_TAG}.json
      prerelease: true
      overwrite: true
      title: "Prerelease ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        include:
          - refs/tags/v**-rc**

  - name: publish-stable
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-canonical-json
      - prepare-release-manifests
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: skip
      files:
        - fury-distribution-${DRONE_TAG}.yml
        - kind-config-${DRONE_TAG}.yml
        - Furyfile.yml
        - kustomization.yaml
        - kfd-canonical-definition-${DRONE_TAG}.json
      prerelease: false
      overwrite: true
      title: "Release ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        exclude:
          - refs/tags/v**-rc**
        include:
          - refs/tags/v**
