# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

kind: pipeline
name: license

steps:
  - name: check
    image: docker.io/library/golang:1.16
    pull: always
    commands:
      - go get -u github.com/google/addlicense
      - addlicense -c "SIGHUP s.r.l" -v -l bsd --check .
---
kind: pipeline
name: policeman

depends_on:
  - license

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    image: quay.io/sighup/policeman
    pull: always
    environment:
      # Identifies false positives like missing 'selector'.
      # Doing this is valid for Kustomize patches
      VALIDATE_KUBERNETES_KUBEVAL: "false"
      # Some duplicated code is intended.
      VALIDATE_JSCPD: "false"
    depends_on:
      - clone

  - name: render
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.19.11_3.8.7_2.4.1
    pull: always
    depends_on:
      - clone
    commands:
      - furyctl vendor -H
      - kustomize build . > distribution.yml

  - name: deprek8ion
    image: eu.gcr.io/swade1987/deprek8ion:1.1.34
    pull: always
    depends_on:
      - render
    commands:
      - /conftest test -p /policies distribution.yml

---
kind: pipeline
name: e2e-kubernetes-1.19

depends_on:
  - policeman

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**
      - refs/heads/master
      - refs/heads/release_1.7.0

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.12.0
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: custom-cluster-119
      pipeline_id: cluster-119
      local_kind_config_path: katalog/tests/config/kind-config-custom
      cluster_version: '1.19.11'
      instance_path: /shared
      instance_size: 2-extra-large
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password

  - name: test
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.19.11_3.8.7_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-119
      - bats -t katalog/tests/install.sh
      - bats -t katalog/tests/networking.sh
      - bats -t katalog/tests/monitoring.sh
      - bats -t katalog/tests/logging.sh
      - bats -t katalog/tests/ingress.sh
      - bats -t katalog/tests/dr.sh
      - bats -t katalog/tests/opa.sh

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.12.0
    depends_on: [ test ]
    settings:
      action: destroy
      pipeline_id: cluster-119
      instance_size: 2-extra-large
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}

---
kind: pipeline
name: e2e-kubernetes-1.20

depends_on:
  - policeman
  - e2e-kubernetes-1.19

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**
      - refs/heads/master
      - refs/heads/release_1.7.0

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.12.0
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: custom-cluster-120
      pipeline_id: cluster-120
      local_kind_config_path: katalog/tests/config/kind-config-custom
      cluster_version: '1.20.7'
      instance_path: /shared
      instance_size: 2-extra-large
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password

  - name: test
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.20.7_3.8.7_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-120
      - bats -t katalog/tests/install.sh
      - bats -t katalog/tests/networking.sh
      - bats -t katalog/tests/monitoring.sh
      - bats -t katalog/tests/logging.sh
      - bats -t katalog/tests/ingress.sh
      - bats -t katalog/tests/dr.sh
      - bats -t katalog/tests/opa.sh

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.12.0
    depends_on: [ test ]
    settings:
      action: destroy
      pipeline_id: cluster-120
      instance_size: 2-extra-large
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}

---
kind: pipeline
name: e2e-kubernetes-1.21

depends_on:
  - policeman
  - e2e-kubernetes-1.19
  - e2e-kubernetes-1.20

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**
      - refs/heads/master
      - refs/heads/release_1.7.0

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.12.0
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: custom-cluster-121
      pipeline_id: cluster-121
      local_kind_config_path: katalog/tests/config/kind-config-custom
      cluster_version: '1.21.1'
      instance_path: /shared
      instance_size: 2-extra-large
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password

  - name: test
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.21.1_3.8.7_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-121
      - bats -t katalog/tests/install.sh
      - bats -t katalog/tests/networking.sh
      - bats -t katalog/tests/monitoring.sh
      - bats -t katalog/tests/logging.sh
      - bats -t katalog/tests/ingress.sh
      - bats -t katalog/tests/dr.sh
      - bats -t katalog/tests/opa.sh

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.12.0
    depends_on: [ test ]
    settings:
      action: destroy
      pipeline_id: cluster-121
      instance_size: 2-extra-large
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}

---
kind: pipeline
name: e2e-kubernetes-1.22

depends_on:
  - policeman
  - e2e-kubernetes-1.19
  - e2e-kubernetes-1.20
  - e2e-kubernetes-1.21

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**
      - refs/heads/master
      - refs/heads/release_1.7.0

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.12.0
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: custom-cluster-122
      pipeline_id: cluster-122
      local_kind_config_path: katalog/tests/config/kind-config-custom
      cluster_version: '1.22.0'
      instance_path: /shared
      instance_size: 2-extra-large
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password

  - name: test
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.22.0_3.8.7_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-122
      - bats -t katalog/tests/install.sh
      - bats -t katalog/tests/networking.sh
      - bats -t katalog/tests/monitoring.sh
      - bats -t katalog/tests/logging.sh
      - bats -t katalog/tests/ingress.sh
      - bats -t katalog/tests/dr.sh
      - bats -t katalog/tests/opa.sh

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.12.0
    depends_on: [ test ]
    settings:
      action: destroy
      pipeline_id: cluster-122
      instance_size: 2-extra-large
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}

---
kind: pipeline
name: release

depends_on:
  - e2e-kubernetes-1.19
  - e2e-kubernetes-1.20
  - e2e-kubernetes-1.21
  - e2e-kubernetes-1.22

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

steps:
  - name: prepare-release-manifests
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.18.19_3.8.7_2.4.1
    pull: always
    depends_on: [ clone ]
    environment:
      RELEASE_MANIFESTS_PATH: fury-distribution-${DRONE_TAG}.yml
    commands:
      - furyctl vendor -H
      - kustomize build . > $${RELEASE_MANIFESTS_PATH}
      - cp katalog/tests/config/kind-config-custom kind-config-${DRONE_TAG}.yml
    when:
      ref:
        include:
          - refs/tags/**

  - name: prepare-release-notes
    image: python:3.7
    pull: always
    depends_on: [ clone ]
    environment:
      RELEASE_NOTES_FILE_PATH: release-notes.md
    commands:
      - pip install semantic_version==2.8.4
      - python -u release-notes.py
    when:
      ref:
        include:
          - refs/tags/**

  - name: publish-prerelease
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-release-manifests
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: skip
      files:
        - fury-distribution-${DRONE_TAG}.yml
        - kind-config-${DRONE_TAG}.yml
        - Furyfile.yml
        - kustomization.yaml
      prerelease: true
      overwrite: true
      title: "Prerelease ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        include:
          - refs/tags/v**-rc**

  - name: publish-stable
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-release-manifests
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: skip
      files:
        - fury-distribution-${DRONE_TAG}.yml
        - kind-config-${DRONE_TAG}.yml
        - Furyfile.yml
        - kustomization.yaml
      prerelease: false
      overwrite: true
      title: "Release ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        exclude:
          - refs/tags/v**-rc**
        include:
          - refs/tags/v**
