# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

- name: Verify that the cluster exists
  hosts: master
  become: true
  tasks:
    - name: Check that the /etc/kubernetes/admin.conf exists
      stat:
        path: /etc/kubernetes/admin.conf
      register: admin_conf_stat

    - name: Set fact if admin.conf exists
      set_fact:
        admin_conf_exists: "{{ admin_conf_stat.stat.exists }}"
      when: admin_conf_stat.stat.exists

- name: Aggregate results and fetch admin.conf
  hosts: master
  tasks:
    - name: Pick a master that has admin.conf
      set_fact:
        admin_conf_host: "{{ item }}"
      loop: "{{ groups['master'] }}"
      when:
        - admin_conf_host is not defined
        - hostvars[item].admin_conf_exists is defined

    - name: Getting admin.conf kubeconfig
      become: yes
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ kubernetes_kubeconfig_path }}/admin.conf"
        flat: yes
      delegate_to: "{{ admin_conf_host | default(inventory_hostname) }}"
      when: admin_conf_host is defined
      run_once: true
